services:

  userman-service:
    image: openjdk:22-jdk-oracle
    container_name: usermanimage
    ports:
      - "8081:8080"
      - "8001:8000"
    expose:
      - "8001"
    depends_on:
      - userman-db
    networks:
      - userman-net
    volumes:
      - ./build/libs/UserManagementService-v0.0.4.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  userman-db:
    image: mongo:latest
    container_name: usermandb
    ports:
      - "27016:27017"
    volumes:
      - mongo_userman:/etc/mongo
      - mongo_userman_data:/data/db
      - mongo_userman_config:/data/configdb
    networks:
      - userman-net

networks:
  userman-net:
    name: userman_net
    driver:
      "bridge"

volumes:
    mongo_userman:
    mongo_userman_data:
    mongo_userman_config:
